### ISSUE TITLE
How to change the font size in the editor

### ISSUE THREAD

**Issue by maggie4406** [dzmipt/kdbStudio#129]
The font size of q codes seem too small for me. I am trying to find the settings to change font size. seems there is no such option.

**Comment by dzmipt** [comment]
This one duplicates https://github.com/dzmipt/kdbStudio/issues/81

**Comment by dzmipt** [comment]
Also last time, unfortunately I don't have time to develop this project.
However there is a different fork (https://github.com/finos/kdb-studio). They took all functionality from my repo (probably there is only one feature which is not present in the FINOS repo).

**Comment by dzmipt** [comment]
As for my repo, there is a workaround to change the font is to ament ~/.studioforkdb/studio.properties file. The properties which you are after are font.size and font.name.
