### ISSUE TITLE
Let's add QPad server configuration import

### ISSUE THREAD

**Issue by dzmiptdb** [dzmipt/kdbStudio#27]

**Comment by dzmipt** [comment]
Format of a config is a text file in a format:
`:host:port:<username>:<password>`folder`subFolder`subSubFolder

The file can have any empty lines. Also anything which doesn't match to the above will be ignored

**Comment by dzmipt** [comment]
If the password could be in a format of <auth mechanism name>?something

**Comment by dzmipt** [comment]
Default file name is Server.cfg. A location should be selected by a user.
