### ISSUE TITLE
Error in rendering result

### ISSUE THREAD

**Issue by dzmipt** [dzmipt/kdbStudio#9]
Played with such object:
get `:test1/ set ([] qqq:1.1 2.2 3.3 4.4 5.5; c:{ ([] a:x+til 3; b: til 3)}  each til 5)

Got the following Exception:
Error occurred during query execution: kx.c$K4Exception: `type
kx.c$K4Exception: `type
	at kx.c.k(c.java:678)
	at kx.c$1.run(c.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dzmipt** [comment]
The issue exist in the latest c.java:
https://github.com/KxSystems/javakdb/issues/51

**Comment by dzmiptdb** [comment]
Another way to have error (probably it is the same problem):
`:sp/ set ([]a:1 2 3;b:10 20 30)
k)+(`a`b)!`/:.Q.dd[`:.;`:.],`sp
