### ISSUE TITLE
Ctrl+Backspace does nothing

### ISSUE THREAD

**Issue by Yanpas** [dzmipt/kdbStudio#90]
But should delete a word (should delete from cursor to Ctrl+Shift+Left selection)

Ctrl+Delete as well

**Comment by dzmipt** [comment]
I am looking to replace Netbeans editor with this one: https://github.com/bobbylight/RSyntaxTextArea
I think it has such action by default

**Comment by dzmipt** [comment]
This action is implemented in new editor
